[package]
name = "wmtoolchain"
version = "0.1.0"
edition = "2024"

[dependencies]
wmarchive = { path = "../wmarchive" }
wmcompiler = { path = "../wmcompiler" }
wmext = { path = "../wmext" }
wmplatform = { path = "../wmplatform" }
wmresource = { path = "../wmresource" }
wmruntime = { path = "../wmruntime" }
wmvm = { path = "../wmvm" }
