[workspace]
resolver = "2"
members = [
    "crates/wms",
    "crates/wmarchive",
    "crates/wmbytecode",
    "crates/wmcompiler",
    "crates/wmext",
    "crates/wmhost",
    "crates/wmplatform",
    "crates/wmfrontend",
    "crates/wmtoolchain",
    "crates/wmui",
    "crates/wmresource",
    "crates/wmruntime",
    "crates/wmverifier",
    "crates/wmvm",
]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false
