[workspace]
resolver = "2"
members = [
    "crates/wmlarchive",
    "crates/wmlbytecode",
    "crates/wmlcompiler",
    "crates/wmlext",
    "crates/wmlhost",
    "crates/wmlplatform",
    "crates/wmlresource",
    "crates/wmlverifier",
    "crates/wmlvm",
]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false
