[package]
name = "wmlfrontend"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", default-features = false, features = ["default_fonts", "glow"] }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
wmlplatform = { path = "../wmlplatform" }
wmlresource = { path = "../wmlresource" }
wmlruntime = { path = "../wmlruntime" }
wmltoolchain = { path = "../wmltoolchain" }
wmlvm = { path = "../wmlvm" }
wmlui = { path = "../wmlui" }
