[package]
name = "wmltoolchain"
version = "0.1.0"
edition = "2024"

[dependencies]
wmlarchive = { path = "../wmlarchive" }
wmlcompiler = { path = "../wmlcompiler" }
wmlplatform = { path = "../wmlplatform" }
wmlresource = { path = "../wmlresource" }
wmlruntime = { path = "../wmlruntime" }
wmlvm = { path = "../wmlvm" }
