[package]
name = "wmlruntime"
version = "0.1.0"
edition = "2024"

[dependencies]
wmlarchive = { path = "../wmlarchive" }
wmlbytecode = { path = "../wmlbytecode" }
wmlhost = { path = "../wmlhost" }
wmlext = { path = "../wmlext" }
wmlplatform = { path = "../wmlplatform" }
wmlresource = { path = "../wmlresource" }
wmlverifier = { path = "../wmlverifier" }
wmlvm = { path = "../wmlvm" }
wmlcompiler = { path = "../wmlcompiler" }
