package = "novelgame"
platform = "egui"
font = "noto"

[[package]]
name = "ui"
entry = "ui/main.wms"

[[package]]
name = "loader"
entry = "loader/main.wms"

[[package]]
name = "engine"
entry = "engine/main.wms"

[[image]]
name = "scene/common"
path = "background.png"

[[image]]
name = "scene/sea"
path = "sea.png"

[[image]]
name = "scene/shelf"
path = "shelf.png"

[[image]]
name = "scene/lamp"
path = "lamp.png"
